name = "JuliaGraphsAlgorithms"
uuid = "622ce888-374a-4ab0-80cf-06934e81c84e"
authors = ["mromrom <moiromrom@alum.us.es> and contributors"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"

[compat]
Graphs = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
